### ISSUE TITLE
More intuitive delegates

### ISSUE THREAD

**Issue by thomasfn** [UnrealSharp/UnrealSharp#100]
Currently you have to declare delegates a specific and non-intuitive a way for them to work, e.g.
```C#
public partial class TestDelegate : MulticastDelegate<TestDelegate.Signature>
{
    public delegate void Signature(string Exception);
}

...

[UProperty(PropertyFlags.BlueprintAssignable)]
public TestDelegate Test { get; set; }
```
It would be nice if delegates were intuitive, e.g. you could just do:
```C#
public delegate void TestDelegate(string Exception);

...

[UProperty(PropertyFlags.BlueprintAssignable)]
public TestDelegate Test { get; set; }
```
The source gen and/or the weaver would take care of generating the delegate class and all the other needed boilerplate. There would need to be some way to mark it as a multicast delegate - maybe a flag to `UProperty`, or maybe we add a `UDelegate` attribute for the delegate?

**Comment by StonedHackerman** [comment]
you could the part in the source generator where you can explore the syntax tree, make a list of all the delegate types used in UProperties in the whole code and generate whatever is needed for them automagically

**Comment by OlssonDev** [comment]
Fixed here: https://github.com/UnrealSharp/UnrealSharp/pull/183
