### ISSUE TITLE
Unreal Engine 5.4

### ISSUE THREAD

**Issue by MulleDK19** [UnrealSharp/UnrealSharp#111]
I know 5.4 is still in preview, but the prerequisites says Unreal Engine 5.3+, so I spent 2 hours installing 5.4 only to realize it doesn't actually work with anything but 5.3 because there are some breaking changes.

**Comment by OlssonDev** [comment]
Thank you. We'll not update UnrealSharp to 5.4 before we got a full version. I just updated the read me to clarify the version support. 

Sorry for the inconvenience
