### ISSUE TITLE
How to get world context?

### ISSUE THREAD

**Issue by etherealbacon** [UnrealSharp/UnrealSharp#120]
Hello,

Firstly, thank you for all of the effort that has gone into this project. 

The wiki suggests the following code:

`StaticMeshActor.Spawn(worldContextObject, MyActorClass);`

Could you tell me how to get the worldContextObject ?

I have search source but have had no luck. 

Thanks!

**Comment by thomasfn** [comment]
If you're in the context of an actor or any object that exists in the world, you can just pass `this` as the world context object. Otherwise (for example in a BP library), you can add a parameter for it with some metadata to make BP fill it in automatically, e.g.

```C#
[UFunction(FunctionFlags.BlueprintCallable), UMetaData("WorldContext", "worldContextObject")]
public static void MyContextlessFunction(Object worldContextObject)
{
    // ...
}
```
