### ISSUE TITLE
 [UFunction(FunctionFlags.BlueprintEvent)] decorated functions dont seem to work when defining a return type

### ISSUE THREAD

**Issue by etherealbacon** [UnrealSharp/UnrealSharp#125]
I have an event and it seems to accept custom structs pretty nicely. 
 
 [UFunction(FunctionFlags.BlueprintEvent)] decorated functions dont seem to work when defining a return type

eg
```
This works:
 [UFunction(FunctionFlags.BlueprintEvent)]
 public void ABCEvent(MyStruct testStruct)
 {

 }
 this doesnt:
 
  [UFunction(FunctionFlags.BlueprintEvent)]
 public MyStruct ABCEvent(MyStruct testStruct)
 {

 }
```
 Thanks for the great work!

**Comment by Duroxxigar** [comment]
Just tested this with latest. Experienced no issues. Everything work as expected.
