### ISSUE TITLE
[UFUNCTION Flags] Missing Flag "CallInEditor"

### ISSUE THREAD

**Issue by ySion** [UnrealSharp/UnrealSharp#129]
I wanna extending my editor tools use UAssetActionUility, but Attribute UFUNCTION missing "CallInEditor" flag in c# version.

**Comment by OlssonDev** [comment]
Oh, thank you! I'll add that!

**Comment by OlssonDev** [comment]
You can already do this :D

```c#
[UClass, UMetaData("CallInEditor", "true")]
```

or

```c#
[UClass, UMetaData("CallInEditor")]
```

**Comment by OlssonDev** [comment]
Thank you :D 

Fixed in an upcoming commit.
