### ISSUE TITLE
BadImageFormatException Error When Using BlueprintEvent

### ISSUE THREAD

**Issue by PourrezJ** [UnrealSharp/UnrealSharp#144]
I am encountering an issue when using BlueprintEvent in my project with version 5.3.2. Every time I try to use a BlueprintEvent, I encounter a BadImageFormatException error.

Here is an example of the code where I am using BlueprintEvent:

```
[UFunction(FunctionFlags.BlueprintEvent)]
public extern void Crouch();

[UFunction(FunctionFlags.BlueprintEvent)]
public extern void AddMappingContext(InputMappingContext mappingContext, ModifyContextOptions options = default);
```

I have ensured that all my dependencies are up to date and that I have not made significant changes to my code recently.

**Comment by PourrezJ** [comment]
I updated the code to version 5.4, I still have the same error.

**Comment by OlssonDev** [comment]
If you use extern, you need to implement it in BP.
