### ISSUE TITLE
Building UnrealSharp as plugin - VS 2022

### ISSUE THREAD

**Issue by krtek2k** [UnrealSharp/UnrealSharp#153]
Cant rebuild the project UnrealSharp after downloading the source from github.

Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.10.2
dotnet-sdk-8.0.302-win-x64 installed
Unreal Engine 5.4.2 installed

Build log https://pastebin.com/raw/GJGcraDM

error CS8802: Only one compilation unit can have top-level statements.

**Comment by OlssonDev** [comment]
Can you post the .csproj file in ProjectFolder/Script folder?

**Comment by krtek2k** [comment]
CMD: dotnet—version
'dotnet-version' is not recognized as an internal or external command,
operable program or batch file.

looks like Visual Studio says I don't have .NET SDK installed- I am at the very least missing a Sys environment variable


After running ProjectFolder/.uproject
![image](https://github.com/UnrealSharp/UnrealSharp/assets/12639639/ceac29b9-95a1-41f8-9092-41b04c5d09d2)
could not be compiled try manually

Generate Visual Studio project files
![image](https://github.com/UnrealSharp/UnrealSharp/assets/12639639/7a6c4327-9df2-4c0a-a252-c2893e34b409)


There is no /Script folder yet

**Comment by krtek2k** [comment]
I have added dotnet path to advanced system settings-> Environment variables-> user variables. Path = "C:\Program Files\dotnet"

fixed the 
dotnet --version
8.0.302

rebuild still the same

**Comment by krtek2k** [comment]
> Can you post the .csproj file in ProjectFolder/Script folder?

misunderstanding where I am stuck at. its at the "Compiling UnrealSharp" - Compile the plugin as any other Unreal Engine plugin using the IDE of your choice; from the Get started guide

**Comment by krtek2k** [comment]
missing the UE project binaries, have to compile it by myself to be able to compile the plugin
