### ISSUE TITLE
FText is not working properly

### ISSUE THREAD

**Issue by MrRobinOfficial** [UnrealSharp/UnrealSharp#164]
Currently, I'm having a couple issue when exporting `Text` to Blueprint.

From my code:

```csharp
// EditorUtils.ExposeWrite = PropertyFlags.BlueprintReadWrite | PropertyFlags.EditAnywhere;

 [UProperty(EditorUtils.ExposeWrite, Category = "Details")]
 public Text? Description { get; private set; }
```

This will cause a crash, since it's null and C++ tries to rebuild the text, which what I gather from this crash reporter:

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UnrealEditor_Core!FText::Rebuild() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Internationalization\Text.cpp:1161]
UnrealEditor_Core!FText::IsEmpty() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Internationalization\Text.cpp:296]
UnrealEditor_CoreUObject!FTextProperty::Identical_Implementation() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\TextProperty.cpp:63]
UnrealEditor_CoreUObject!FTextProperty::Identical() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\TextProperty.cpp:117]
UnrealEditor_CoreUObject!UStruct::SerializeVersionedTaggedProperties() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:1752]
UnrealEditor_CoreUObject!UStruct::SerializeTaggedProperties() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:1334]
UnrealEditor_CoreUObject!UObject::SerializeScriptProperties() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Obj.cpp:1880]
UnrealEditor_CoreUObject!UObject::Serialize() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Obj.cpp:1661]
UnrealEditor_Engine!UDataAsset::Serialize() [D:\build\++UE5\Sync\Engine\Intermediate\Build\Win64\UnrealEditor\Inc\Engine\UHT\DataAsset.gen.cpp:95]
```
I try to use other solution, but none of them worked.

If you assign the variable with a value of `string.Empty`, `""` or `Text.None`, it will still cause a crash. However, this time, the report is coming from dotnet tool, and says:

```
dotnet task failed: 
 An error occurred: Error in executing build command : 
Error during assembly processing: Property initializer for UProperty Description is not a supported constant type
F:\Projects\Unreal Projects\Exodus\Script\src\Gameplay\Systems\Inventory\ItemDefinition.cs(31) : error UnsupportedPropertyInitializerException: Caught fatal error: Property initializer for UProperty Description is not a supported constant type


Failed to initialize action.
```

And creating a constant variable, which Text then refers to, will still not make any difference. **Note as well**, changing the variable from being nullable to non-nullable, it will not make any differences.

I also change the data type to C# `string`, which then worked. But yet again, it detects now as `FString`, rather than `FText`.

![Screenshot 2024-07-22 125211](https://github.com/user-attachments/assets/81569e41-76d4-4eee-83b1-c3641bb6c9e5)

**Comment by JothamR** [comment]
This is still an issue, but it appears to be tied to the value being `null` 

The below test code works (for both a UProperty exposed `string` or `FText`), but it crashes immediately if you remove setting the default value in the constructor.

```
using UnrealSharp.Attributes;
using UnrealSharp.CoreUObject;
using UnrealSharp.UMG;

[UClass]
public class UUserWidget_CSharp : UUserWidget
{
    [UProperty(PropertyFlags.BlueprintReadOnly)]
    public required string TestString { get; set; }

    public UUserWidget_CSharp()
    {
        TestString = string.Empty; //!!!IMPORTANT - UE CRASHES HARD if a UPROPERTY string (or FText) is ever null
    }
}
```

**Comment by JothamR** [comment]
FYI - had some luck fixing `string` by updating `StringMarshaller` in Marshallers.cs 
with some null pointer guard code to (`ToNative`,`FromNative` and `DestructInstance`) i.e.

`if (nativeBuffer == IntPtr.Zero) return;`
`if (nativeBuffer == IntPtr.Zero) return string.Empty;`

**Comment by JothamR** [comment]
P.S. FText still blows up Unreal if left as null - checking whether there's something we can do on the FText side, but still getting my head around how the magic of this plugin works

**Comment by JothamR** [comment]
Splitting out the null string fix to this PR: https://github.com/UnrealSharp/UnrealSharp/pull/232

So, this issue is back to tracking just the FText issue as originally described.

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/commit/32bb086a808a9b6160037f261ef31bc279ecaa54
