### ISSUE TITLE
Unable to load script assembly in package

### ISSUE THREAD

**Issue by Liangjia0411** [UnrealSharp/UnrealSharp#171]
I created a demo project in the 5.3.2 engine and integrated it with the Unreal Sharp plugin; After packaging, running the game will result in the following error:`The bindings library could not be found at the following location:
D:/Code/UnrealSharpDemo/Binaries/Managed/UnrealSharp.Plugins.dll`

What should I do

**Comment by OlssonDev** [comment]
Follow this: https://www.unrealsharp.com/packaging.html

**Comment by Liangjia0411** [comment]
thank you
