### ISSUE TITLE
How does Console.WriteLine work in the UnrealSharp.Plugins C# project?

### ISSUE THREAD

**Issue by Liangjia0411** [UnrealSharp/UnrealSharp#185]
Hello,

I am working with the `UnrealSharp.Plugins` C# project and have encountered an issue with `Console.WriteLine`. Specifically, I am not seeing any output.

Could you please explain how Console.WriteLine is supposed to work in this project? Are there any specific configurations or settings that I need to check to ensure that the output is visible?

Thank you!

**Comment by OlssonDev** [comment]
The printing to console works as expected for me. If you want to print to the log in UE, use this that exists for every UObject:

```
    public void PrintToConsole(string message = "Hello")
    {
        PrintString(message, printToScreen: false);
    }
```

**Comment by Liangjia0411** [comment]
How to use console to run the game

**Comment by OlssonDev** [comment]
Not sure I understand

**Comment by Liangjia0411** [comment]
> The printing to console works as expected for me
Where can I view the content output to the console

**Comment by OlssonDev** [comment]
In your IDE
