### ISSUE TITLE
Can you provide some basic usage documents

### ISSUE THREAD

**Issue by anan1213095357** [UnrealSharp/UnrealSharp#186]
![image](https://github.com/user-attachments/assets/90a247da-2f14-423f-b490-f34930ce3090)
For example, when I create in this way, there are always errors. Can I create without using quaternions? This is very unfriendly for beginners

**Comment by OlssonDev** [comment]
What is the error?

**Comment by anan1213095357** [comment]
> What is the error?

This code will exit directly. I didn't catch what the error was. Is there any correct usage of these APIs?

**Comment by OlssonDev** [comment]
Then it's probably a bug. I'll check it out! Also I'll add FRotator => FQuat

**Comment by anan1213095357** [comment]
> Then it's probably a bug. I'll check it out! Also I'll add FRotator => FQuat

Excuse me, I'm a beginner and only C # can help me use UE smoothly. I can't be of any help to you, sorry.

**Comment by OlssonDev** [comment]
Yes, and I'll try to fix this issue.

**Comment by anan1213095357** [comment]
> Yes, and I'll try to fix this issue.

Can I create using this function now?
