### ISSUE TITLE
Inadequate Validation of UObject in C++ UFunction Calls？

### ISSUE THREAD

**Issue by Liangjia0411** [UnrealSharp/UnrealSharp#195]
When calling C++ UFunction in C#, the IsValid method is not as effective as FWeakObjectPtr in determining whether a UObject has been destroyed. Below is a relevant code example:
```c++
void* UAActorExporter::GetRootComponent(AActor* Actor)
{
    if (!IsValid(Actor))
    {
        return nullptr;
    }
    
    return FCSManager::Get().FindManagedObject(Actor->GetRootComponent()).GetIntPtr();
}
```

**Comment by OlssonDev** [comment]
What do you mean?

**Comment by Liangjia0411** [comment]
![image](https://github.com/user-attachments/assets/3b9268bd-f59d-4e09-b70e-7c0ade96a60b)
![image](https://github.com/user-attachments/assets/1c2d7572-038e-44b2-bb8e-6d8e83bd4550)
As shown in the above figure, call GUObject Array IndexToObject (Test ->InternalIndex) will return the FUObjectItem corresponding to the object; The IsVaild method only uses the Flags of FUObjectItem to determine whether an object is valid; But this FUObject Item may belong to another UObject, and the original UObject may already be enough to be destroyed.

**Comment by OlssonDev** [comment]
If our IsValid fails, we have a GC issue on our hands and the problem is elsewhere.
