### ISSUE TITLE
Crash at runtime with dll added to managed project

### ISSUE THREAD

**Issue by bluedub** [UnrealSharp/UnrealSharp#205]
I have added a C# dll to my managed project and when trying to use a type from it UnrealSharp will crash saying it cannot find the assembly even though it is added to the project.

Repro Steps

1. Download the attached dlls 
and add them as dependencies to a project
2. Use one of the types, an example script is below
3. UnrealSharp will crash

```
Exception during InvokeManagedMethod: System.IO.FileNotFoundException: Could not load file or assembly 'EbxTypes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

```
using Frostbite.Entity;
using UnrealSharp.Attributes;
using UnrealSharp.Engine;

namespace ManagedTest;

[UClass]
public class ATestScript : AActor
{
    [UFunction(CallInEditor = true)]
    void Test()
    {
        Type type = typeof(DelayEntityData);
    }
}
```

[ExampleDlls.zip](https://github.com/user-attachments/files/17050642/ExampleDlls.zip)

**Comment by OlssonDev** [comment]
I made a separate class library and imported it, it worked. 

I'm not gonna download a DLL unfortunately.
