### ISSUE TITLE
UCSEditorSubsystem and UCSEngineSubsystem not initializing

### ISSUE THREAD

**Issue by CadeEvs** [UnrealSharp/UnrealSharp#209]
After editing the UCSEditorSubsystem class to use a native event for ShouldCreateSubsystem(), it looks like that function is never called even in the C++ CS subclass. It looks like the subsystem collection isn't collecting/finding the C# subclasses for both the Editor and Engine subsystems.

```
using UnrealSharp.Attributes;
using UnrealSharp.UnrealSharpEditor;

namespace ManagedUnrealSharpRepro;

[UClass]
public class UTestSubsystem : UCSEditorSubsystem
{
    protected override void Initialize()
    {
        base.Initialize();
        
        Console.WriteLine("Initializing DbxSubsystem");
    }
}
```

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/commit/7aeaecd39dd151522bdcb994f6a0c2fde686ebcd
