### ISSUE TITLE
"'UnrealSharp.ObjectMarshaller`1' was used with an invalid instantiation" on function call

### ISSUE THREAD

**Issue by DarthAffe** [UnrealSharp/UnrealSharp#212]
Hey, when running the setup bellow I get the following runtime error.
> Fatal error detected: "System.TypeLoadException: The generic type 'UnrealSharp.ObjectMarshaller`1' was used with an invalid instantiation in assembly 'UnrealSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ACaster.Invoke_GetSpellFromSlot(IntPtr, IntPtr)

My setup contains the c# classes `ACaster` and `USpell`. Both are used as a base class for a blueprint (`BP_Wizard` and `BP_Spell_Blink`).
The `AvailableSpells`-array is filled with a single entry in the construction script of `BP_Wizard`. The `GetSpellFromSlot`-method (which the error is thrown in) is called inside an controller on key-press.

![wizard_construction](https://github.com/user-attachments/assets/66871f76-0483-42cf-80cd-2ae9a7e6dee2)
![controller](https://github.com/user-attachments/assets/f01b52a1-775e-4894-ac49-67ca2682b84b)

```csharp
[UClass]
public partial class USpell : UObject
{    
    [UProperty(PropertyFlags.BlueprintReadWrite)]
    public string Name { get; set; }
}
```

```csharp
[UClass]
public partial class ACaster : ACharacter
{
    [UProperty(PropertyFlags.BlueprintReadWrite)]
    public TArray<USpell> AvailableSpells { get; set; }

    [UFunction(FunctionFlags.BlueprintCallable)]
    public bool Cast(USpell spell)
    {
        PrintString($"Cast {spell.Name}");

        return true;
    }
    
    [UFunction(FunctionFlags.BlueprintCallable)]
    public bool GetSpellFromSlot(int slot, out USpell? spell)
    {
        if ((AvailableSpells == null!) || (slot < 0) || (slot >= AvailableSpells.Count))
        {
            spell = null;
            return false;
        }

        spell = AvailableSpells[slot];
        return true;
    }
}
```

**Comment by OlssonDev** [comment]
Solved: https://github.com/UnrealSharp/UnrealSharp/commit/80cd325fd786fc1eb4aaa5deadc22341605f7ad7
