### ISSUE TITLE
can't biuld c#

### ISSUE THREAD

**Issue by kongbawa** [UnrealSharp/UnrealSharp#213]
dotnet task failed: 
 >>> UnrealSharpBuildTool
Command: C:\Program Files\dotnet\dotnet.exe build G:\Work\UnrealSharp-Cropout\Script --configuration Debug
An error occurred: Error in executing build command : 

  Determining projects to restore...
  所有项目均是最新的，无法还原。
  ProjectGlue -> G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\bin\Debug\net8.0\ProjectGlue.dll
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs(4,12): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(14,12): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(15,12): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(16,12): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(17,12): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(18,12): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(19,12): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(20,12): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\CSharpForUE\CSBlueprintAsyncActionBase.generated.cs(18,28): warning CS0108: “UCSBlueprintAsyncActionBase.Activate()”隐藏继承的成员“UBlueprintAsyncActionBase.Activate()”。如果是有意隐藏，请使用关键字 new。 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\CSharpForUE\CSCancellableAsyncAction.generated.cs(18,28): warning CS0108: “UCSCancellableAsyncAction.Activate()”隐藏继承的成员“UBlueprintAsyncActionBase.Activate()”。如果是有意隐藏，请使用关键字 new。 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\CSharpForUE\CSCancellableAsyncAction.generated.cs(47,28): warning CS0108: “UCSCancellableAsyncAction.Cancel()”隐藏继承的成员“UCancellableAsyncAction.Cancel()”。如果是有意隐藏，请使用关键字 new。 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]

生成失败。

G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\CSharpForUE\CSBlueprintAsyncActionBase.generated.cs(18,28): warning CS0108: “UCSBlueprintAsyncActionBase.Activate()”隐藏继承的成员“UBlueprintAsyncActionBase.Activate()”。如果是有意隐藏，请使用关键字 new。 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\CSharpForUE\CSCancellableAsyncAction.generated.cs(18,28): warning CS0108: “UCSCancellableAsyncAction.Activate()”隐藏继承的成员“UBlueprintAsyncActionBase.Activate()”。如果是有意隐藏，请使用关键字 new。 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\ProjectGlue\CSharpForUE\CSCancellableAsyncAction.generated.cs(47,28): warning CS0108: “UCSCancellableAsyncAction.Cancel()”隐藏继承的成员“UCancellableAsyncAction.Cancel()”。如果是有意隐藏，请使用关键字 new。 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs(4,12): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(14,12): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(15,12): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(16,12): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(17,12): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(18,12): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(19,12): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
G:\Work\UnrealSharp-Cropout\Script\obj\Debug\net8.0\ManagedCropoutSampleProject.AssemblyInfo.cs(20,12): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复 [G:\Work\UnrealSharp-Cropout\Script\ManagedCropoutSampleProject.csproj]
    3 个警告
    8 个错误

已用时间 00:00:00.72

An error occurred: Failed to initialize action.
   at UnrealSharpBuildTool.Program.Main(String[] args) in G:\Work\UnrealSharp-Cropout\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpBuildTool\Program.cs:line 38

**Comment by OlssonDev** [comment]
I can't read the language the error is in
