### ISSUE TITLE
[BUG] FEnumProperty's UnderlyingProp Incorrectly Created as FByteProperty

### ISSUE THREAD

**Issue by Liangjia0411** [UnrealSharp/UnrealSharp#218]
As shown in the following code: Creating UnderlyingProp of FENumProperty as FByteProperty is incorrect behavior?
![image](https://github.com/user-attachments/assets/d1233a29-be97-4a63-a4df-0f2a4a63f64d)

Here is an example of an error:
- When I called `TestEnum` in the blueprint, the output was not the expected result
![image](https://github.com/user-attachments/assets/d3db3a85-e058-45db-b85c-bc742bca5c81)
![image](https://github.com/user-attachments/assets/d80b6d94-e1be-4efb-ad7b-c9e851088b50)

- The reason for this problem is that EBlueprintType is of type int, which causes the value to be obtained based on 4 bytes instead of 1 byte
![image](https://github.com/user-attachments/assets/f544f918-3f4d-4160-9501-ff231650e1df)

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/pull/228 Fixed
