### ISSUE TITLE
BUILD FAILED: Unable to determine UHT module type 

### ISSUE THREAD

**Issue by Piler-Tam** [UnrealSharp/UnrealSharp#221]
Unable to determine UHT module type for D:\Users\A\Documents\Unreal Projects\FirstGameTutorial\Plugins\UnrealSharp-main\Package\HostProject\Plugins\CSharpForUE\Source\UnrealSharpUtilities\UnrealSharpUtilities.Build.cs Took 9.63s to run dotnet.exe, ExitCode=6 UnrealBuildTool failed. See log for more details. (C:\Users\A\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt) AutomationTool executed for 0h 0m 10s AutomationTool exiting with ExitCode=6 (6) BUILD FAILED

**Comment by ezesil** [comment]
Same here, doesn't matter if i use 5.4.2 or 5.3.2 to build, or an older commit.

**Comment by OlssonDev** [comment]
Are there any steps to reproduce this?
