### ISSUE TITLE
[VERSION] UE 5.5 Compatibility

### ISSUE THREAD

**Issue by rob-ack** [UnrealSharp/UnrealSharp#222]
UnrealSharp compatibility is broken in current UE 5.5 preview. Mainly due to changes to EpicGames.UHT classes.
Lets Wait for UE 5.5 release for adoption.

**Comment by b2soft** [comment]
One of errors caused by this change https://github.com/EpicGames/UnrealEngine/commit/f4fefeb1b64feda80e75da6fd1d112952a4d5548

**Comment by MulleDK19** [comment]
5.5 was released today.

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/pull/270
