### ISSUE TITLE
Native set methods should be setters on properties for C#

### ISSUE THREAD

**Issue by Duroxxigar** [UnrealSharp/UnrealSharp#236]
Whenever there is a setter method for a field in C++, UnrealSharp should generate the set side of the property. Not only getters. It is fine to still have support for the method itself, but C# idiom is that setter properties should be preferred.

Recent example - the `bReplicates` field on an actor has a `SetReplicates()` method. We already have it as a property, `Replicates` - but it only has the getter, not a setter. So you have to call `SetReplicates()`. C# style is that it should be `Replicates = true or false`.

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/pull/261
