### ISSUE TITLE
[BUG] Recompile Error with async function with return value

### ISSUE THREAD

**Issue by cocochengang** [UnrealSharp/UnrealSharp#238]
UE 5.4.4
UnrealSharp 0.1

1. BpExampleActor extends from AExampleActor. When AExampleActor is modified again, CS compilation generates an error.

![image](https://github.com/user-attachments/assets/0995341a-9d08-4988-a42c-27790ca0e0f5)
LogBlueprint: Error: [AssetLog] F:\UEPrjs\TestUESharp\Content\Blueprints\BpExampleActor.uasset: [Compiler] This blueprint (self) is not a ExampleActor_C_OLD_119206, therefore ' Target ' must have a connection.

2. When clicking on UE's Compile button, it works fine.

![image](https://github.com/user-attachments/assets/d9cb9874-2583-420d-b00b-5894d8b4d528)

**Comment by rob-ack** [comment]
Can confirm this issue having a different usecase. 

![image](https://github.com/user-attachments/assets/0c445e2e-5a7e-4b74-a759-d15299b2624e)

After c# compiles i always have to refresh the custom event node which is in error state. The parameter of the async function is not matched stable in BPs.
