### ISSUE TITLE
Problems exporting, says it doesn't have the plugin

### ISSUE THREAD

**Issue by kone9** [UnrealSharp/UnrealSharp#240]
![Captura de pantalla 2024-10-19 001400](https://github.com/user-attachments/assets/2d4f559e-b9ea-4605-b801-67bf6eb25a91)

![Captura de pantalla 2024-10-19 001557](https://github.com/user-attachments/assets/4d8b9428-b05a-4431-b5e3-0b7b49fcb1ba)

I'm also running programs from C#, that is, opening processes, because I'm doing some pretty crazy tests.
I don't know if that's the reason.
![Captura de pantalla 2024-10-19 003155](https://github.com/user-attachments/assets/4c75330b-2ff1-408b-83c1-00b58c8ae413)

**Comment by kone9** [comment]
I already saw, I have to export after exporting to the folder where the .exe is the C# part, there it says export... But it still doesn't work. A 2 minute video should be made of that, to avoid confusion.

![Captura de pantalla 2024-10-19 004528](https://github.com/user-attachments/assets/d03be662-0612-4105-8324-a8981e9ba7d3)

**Comment by OlssonDev** [comment]
This is a issue with BP projects, and for now we're not looking into it.

**Comment by kone9** [comment]
> This is a issue with BP projects, and for now we're not looking into it.

I added a c++ class and now it says this
![Captura de pantalla 2024-10-19 232601](https://github.com/user-attachments/assets/09142757-e4fa-42aa-b198-0c888bc0731e)

Fatal error: [File:C:\Users\ARIEL\Documents\Unreal Projects\GardelJobs\Plugins\UnrealSharp\Source\CSharpForUE\CSManager.cpp] [Line: 98] 
Failed to load Runtime Host
