### ISSUE TITLE
[BUG] Opening the C# solution from the U# menu will freeze the UE Editor

### ISSUE THREAD

**Issue by John-Storm** [UnrealSharp/UnrealSharp#249]
![image](https://github.com/user-attachments/assets/db9bbb1f-f17d-45a3-816d-9a3a9e6c99b2)

UE 5.4.4: When clicking that link, the C# solution will open but the UE Editor hangs. Opening the <MyManagedProject>.sln outside of using this shortcut doesn't cause any issue with the UE Editor.

Tested on a new blank game project.

**Comment by Zuriel-Zurichi** [comment]
I don't know if this helps but this only happens to me when I use Visual Studio

**Comment by John-Storm** [comment]
Interesting observation. I use Visual Studio Community 2022. Didn't try with other IDEs.

**Comment by rob-ack** [comment]
I can not confirm this. It is not happening for me. 
I have VS 2022 community too with Version 17.11.5 currently.

**Comment by ezesil** [comment]
Same here using Visual Studio Community 2022 17.10.5 and Unreal Engine 5.4.2 compiled from source. After closing it, it stops freezing. Opening visual studio from outside has no issues. 

It's probably blocking unreal's main thread.

**Comment by NGC717** [comment]
Using UE 5.4.4 and Rider 2024.2.7, encountered the same issue.

**Comment by 349516385** [comment]
also happens to me

**Comment by JothamR** [comment]
Looks like it blocks in UnrealSharpEditor.cpp OpenSolution() on the line:
`FPlatformProcess::ExecProcess(TEXT("cmd.exe"), *OpenSolutionArgs, nullptr, nullptr, nullptr);`

**Comment by JothamR** [comment]
Doesn't look like there's a parameter to make ExecProcess non-blocking, but we could run it as a separate AsyncTask or thread.

As an AsyncTask it'd change to this:
```
	AsyncTask(ENamedThreads::AnyBackgroundThreadNormalTask, [OpenSolutionArgs]() 
	{
		FPlatformProcess::ExecProcess(TEXT("cmd.exe"), *OpenSolutionArgs, nullptr, nullptr, nullptr);
	});
```

**Comment by JothamR** [comment]
I can create an PR with the above as it seems to fix the issue, but happy for someone who knows more about how multi-threading in Unreal works to weigh in.  (e.g. pros/cons of using AsyncTask vs a new thread (via FRunnable?) vs a more standard C++ thread)

**Comment by JothamR** [comment]
scratch the above - `FPlatformProcess::ExecProcess()` blocks, but there's also a non-blocking one  `FPlatformProcess::CreateProcess()`

**Comment by JothamR** [comment]
PR here: https://github.com/UnrealSharp/UnrealSharp/pull/297
