### ISSUE TITLE
Requires manual compile in-editor if you modify managed script while editor isn't open

### ISSUE THREAD

**Issue by CadeEvs** [UnrealSharp/UnrealSharp#252]
It looks like building the managed sln no longer compiles properly, you'll still need to manually compile C# script in-editor.

Relevant conversation https://discord.com/channels/1153570806417342466/1198741275600486592/1299434561805094944

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/commit/02052e4478dd00db290ca4ce0757233ad63360d1
