### ISSUE TITLE
USoundWaveProcedural lacks the QueueAudio function

### ISSUE THREAD

**Issue by hefujie1988** [UnrealSharp/UnrealSharp#257]
USoundWaveProcedural lacks the QueueAudio function. How can I play base64-encoded sound like C++?

**Comment by offleash-oolsson** [comment]
Make a wrapper function that is BlueprintCallable to expose it to C#

**Comment by OlssonDev** [comment]
Expose it to C# through a wrapper function that is BlueprintCallable
