### ISSUE TITLE
[Crash] Calling 'multiDelegate.InnerDelegate.Invoke(actor)' from C# Code will crash the Editor without callstack.

### ISSUE THREAD

**Issue by rob-ack** [UnrealSharp/UnrealSharp#259]
Calling 'multiDelegate.InnerDelegate.Invoke(actor)' from C# Code will crash the Editor without callstack.

Possibly this was never intended but a silent crash should not be happening in any case.

For:
```
[UMultiDelegate]
public delegate void Callback(AActor actor);

...

multiDelegate.InnerDelegate.Invoke(actor);
```

This is not the case for an [USingleDelegate] but with.
```
[USingleDelegate]
public delegate void Callback(AActor actor);

...

singleDelegate.Invoke(actor);
```
which seems to be the intended way. However nothing which will help use here to identify the cause.

**Comment by rob-ack** [comment]
Could you elaborate a bit about the situation so i can understand if it should be possible with multi delegate or if it was not an intended usecase? Depending on this we can then think about how to fix or prevent the case.

**Comment by OlssonDev** [comment]
You should always use Delegate.Invoke
