### ISSUE TITLE
Using the generic `SpawnActor` provided by `UObject` to spawn a `Character` causes a crash, but spawning through the interface exported via reflection works fine.

### ISSUE THREAD

**Issue by redasm** [UnrealSharp/UnrealSharp#282]
![image](https://github.com/user-attachments/assets/3ef471e8-76d6-471a-a6fd-8bf626c60cec)
![image](https://github.com/user-attachments/assets/fe78b12b-a322-4b4d-b5aa-bcb66e255329)
The following interface works fine:
![image](https://github.com/user-attachments/assets/61227f93-fdae-4543-9705-3de326bb51fa)
The following interface causes a crash:
![image](https://github.com/user-attachments/assets/f48a1f2c-beb9-4f1f-bb0e-00c6636023c9)

When you start the engine, you will create two Default Characters from the USharp framework, whether this is due to inheritance on the C# side
![image](https://github.com/user-attachments/assets/d430e2f9-47b8-4581-a7d9-a9e8f899ca46)
When a Character is created when switching levels, there will be 3 Default Characters created, only the last one BP_PlayerCharacter created by my real SpawnActor
![image](https://github.com/user-attachments/assets/8b604f6a-bbac-4ab6-8495-f0b2463f733f)

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/commit/b6b708ae2ca42778628e111e3f970d9c8718b3f0

Try now!
