### ISSUE TITLE
Enum bitmask / bitflags

### ISSUE THREAD

**Issue by markusstephanides** [UnrealSharp/UnrealSharp#287]
An `UEnum` can currently only specify a `Category` and `DisplayName` but not whether the enum is used as bitmask.

More info here: https://unrealcommunity.wiki/bitmask-bitflag-enums-kdq2na6w

**Comment by Tesagi** [comment]
If i'm correct. Many UE metadata properties in U# moved to c# Attrubute classes.
Example UE Bitflags -> BitflagsAttribute

see MetaTags.cs in namespace UnrealSharp.Attributes.MetaTags

```
/// <summary>
/// [Bitflags]
/// Indicates that this enumerated type can be used as flags by integer UPROPERTY variables that are set up with the Bitmask Metadata Specifier.
/// </summary>
[AttributeUsage(AttributeTargets.Enum)]
public sealed class BitflagsAttribute : Attribute { }
```

if some attribute not exist u can use "generic" attribute UMetaData. For example:
```
UENUM(meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
```
equals
```
[UEnum]
[Bitflags]
[UMetaData("UseEnumValuesAsMaskValuesInEditor", "true")]
public enum ETestEnum : byte
{
    [UMetaData("Hidden", "true")]
    None = 0,
    One = 1,
    Two = 2,
    Three = 4,
}
```

**Comment by OlssonDev** [comment]
Use UMetaData
