### ISSUE TITLE
Certain combination of FVector math operations seem to cause an exception when calling SpawnActor

### ISSUE THREAD

**Issue by mars9t** [UnrealSharp/UnrealSharp#291]
Totally clueless what might be the root cause, hence the title pertaining to the surface observations.

Tried to spawn projectiles like in a C++ First Person template. All worked well with base logic.
Then I added additional offset variable to the transform and the editor started to crash after calling SpawnActor, throwing `ExecutionEngineException`.

Base setup:
![image](https://github.com/user-attachments/assets/4c2ae7e5-c224-4a73-85ed-fef2d2f75f06)

Simply created and added offset FVector:
![image](https://github.com/user-attachments/assets/ef2db62e-c1f6-42f1-ac2c-8bdf1cb3c9ef)

Exception:
![image](https://github.com/user-attachments/assets/9d09b953-067b-48e1-ae8a-7ab34a3a7afd)
![image](https://github.com/user-attachments/assets/db5f0bc8-c6c0-438b-9e8e-bd2c53d2e308)

Debugging shows the location value is rather ok, including when dereferencing the transform inside CallSpawnActor:
![image](https://github.com/user-attachments/assets/41fa6d4a-8149-4f04-b77b-f0f145e0399d)
![image](https://github.com/user-attachments/assets/7c2807e5-4e63-4aa5-bd3e-de769127c0c0)

There are configurations of it being added that end catastrophically. Here are some that work and some that don't:
![image](https://github.com/user-attachments/assets/c17841f9-63b6-4e99-bbde-0291fd17f59e)

Will isolate the problem more and upload project files when possible.

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/commit/b6b708ae2ca42778628e111e3f970d9c8718b3f0

Fixed!
