### ISSUE TITLE
[CRASH] Call from a BlueprintCallable calling into a BlueprintEvent implemented in blueprints will crash the editor.

### ISSUE THREAD

**Issue by rob-ack** [UnrealSharp/UnrealSharp#292]
the code which will lead to the crash:
![image](https://github.com/user-attachments/assets/cf909a46-45cc-47eb-8a9f-858eb2462e5e)

`UpdateData_Test` is invoked from a PB implementing the `CreateTargetWidget`.

code from the blueprint implementing this event will be called and can be debugged. after the blueprint implementation returns, the crash will accrue.

**Comment by rob-ack** [comment]
I figured out that the crash happens because the BlueprintEvent `CreateTargetWidget` has an parameter. removing the parameter will get the code running without crash.

**Comment by OlssonDev** [comment]
I can't reproduce this on latest main

**Comment by rob-ack** [comment]
Not solved. Can still reproduce it. Im going to create a reproduction project!

**Comment by rob-ack** [comment]
@OlssonDev Here is the test project recreating the crash from 'Untitled.umap'.
[UnrealSharpTestBase.zip](https://github.com/user-attachments/files/18136896/UnrealSharpTestBase.zip)
