### ISSUE TITLE
Error : CS1001  at 3DWidget = 2

### ISSUE THREAD

**Issue by thinbug** [UnrealSharp/UnrealSharp#306]
`using UnrealSharp.Engine;

public enum ETraceChannel
{
	Visibility = 0,
	Camera = 1,
	3DWidget = 2,
}

public static class TraceChannelStatics
{
	public static ETraceTypeQuery ToQuery(this ETraceChannel traceTypeQueryHelper)
	{
		return (ETraceTypeQuery)traceTypeQueryHelper;
	}
}`
New project after plug-in installation enter prompt create project generated script error here.
Error : CS1001  at 3DWidget = 2

**Comment by OlssonDev** [comment]
Right, thank you! Numbers are not valid as enum names, as a quick fix before I fix this edge case, change the collision profile name.
