### ISSUE TITLE
Document how to use F# in Script solution

### ISSUE THREAD

**Issue by bitstormFA** [UnrealSharp/UnrealSharp#307]
First of all - this is a fantastic project! 

I started implementing some simple scripts and everything looks very promising.
 
One thing I noticed, is that it seems now actually to be possible to use Unreal from F# - simply by creating a new F# project in the Script solution.

Although this might be a niche use case, I could imagine that this would produce additional visibility for this project, if this is what you are looking for at the moment.

I did not do any real tests so far - if I overlooked some fundamental problems with this idea - please excuse my oversight.

**Comment by OlssonDev** [comment]
Officially I'll not add F# support, but I'm happy to look at PRs that makes it possible.

**Comment by ShalokShalom** [comment]
F# support already exists. 

It would mostly be a job to document it, but the language itself goes at great lengths to stay compatible with C#.

It has a fully capable object system, for once.
