### ISSUE TITLE
Additional scene component is created if C# script doesn't have a default scene root

### ISSUE THREAD

**Issue by Duroxxigar** [UnrealSharp/UnrealSharp#315]
I believe this commit (https://github.com/UnrealSharp/UnrealSharp/commit/00fd3d09593a38d03129fabe284bab0b17887144) is causing the behavior. Create a BP and inherit from character. Create a C# script as a child of ACharacter. Don't have the root component set in the script and then reparent the BP to the new C# parent. A new DefaultSceneRoot component is created (although, not at the root)

**Comment by rob-ack** [comment]
fixed with 3b96972ddf63f6a7c7c8b47c134680c88d3370b3
