### ISSUE TITLE
Missing UClass specifiers

### ISSUE THREAD

**Issue by Duroxxigar** [UnrealSharp/UnrealSharp#35]
It doesn't appear all UClass specifiers are exposed. One notable one is BlueprintSpawnableComponent

![image](https://github.com/UnrealSharp/UnrealSharp/assets/16636969/9019ed52-f079-4175-a815-1ad51971f460)

**Comment by thomasfn** [comment]
`BlueprintSpawnableComponent` is metadata not a class flag, you can apply it using `[UMetaData("BlueprintSpawnableComponent")]`
