### ISSUE TITLE
SetActorLocation moves the Actor to Vector(0, 0, 0)

### ISSUE THREAD

**Issue by tzainten** [UnrealSharp/UnrealSharp#46]
My code:
![image](https://github.com/UnrealSharp/UnrealSharp/assets/122052876/d23ddfc2-c393-4eb1-8e1f-7cac9c615732)

Before clicking Play:
![image](https://github.com/UnrealSharp/UnrealSharp/assets/122052876/98425f21-ccb7-4259-9268-e643626a2cb2)

After clicking Play:
![image](https://github.com/UnrealSharp/UnrealSharp/assets/122052876/33dcdff8-cdd6-41f2-9f28-2ba377125aee)

**Comment by tzainten** [comment]
I did some additional testing and I think this might have something to do with out parameters? I created my own UFunctions to test this out and this is what I found.

This moves the Actor to the correct location:
![image](https://github.com/UnrealSharp/UnrealSharp/assets/122052876/1b2a809f-11c6-4642-aafd-fa8915479b3b)

This fails and moves the Actor to Vector(0, 0, 0):
![image](https://github.com/UnrealSharp/UnrealSharp/assets/122052876/47f929ba-61be-45ba-9599-9ee163d5a97c)

**Comment by OlssonDev** [comment]
Thank you! I'll test it out tonight.

**Comment by OlssonDev** [comment]
Fixed in the latest change 👍
