### ISSUE TITLE
Question : Is the full power of .net supported (including adding nuget or other packages) or only a limited set ?

### ISSUE THREAD

**Issue by gm0124816** [UnrealSharp/UnrealSharp#54]
First of all, nice work !

Unfortunately it is not all that clear if the full set of .net 8 will be supported or just a limited set. Especially the possibility to add extra packages via nuget for instance or own libraries in c# would be great (and of course correctly packaged for runtime as well) !

I know verse is coming, but really, yet another language to learn ... ... I need more fingers to count the number of languages I'm supposed to know 'in depth' these days ...

Anyway, keep up the good work !

**Comment by OlssonDev** [comment]
It's vanilla .NET 8.0. You can add any nuget packages you want.
