### ISSUE TITLE
Conflicting plugins

### ISSUE THREAD

**Issue by gm0124816** [UnrealSharp/UnrealSharp#55]
I noticed that some of the unreal plugins can conflict with namings in your project and that of course causes a failed build. One of these plugins is :

https://www.unrealengine.com/marketplace/en-US/product/eventdispatcher

The name 'eventdispatcher' conflicts with namings used in USharp.

Maybe it is possible to rename 'obvious' names to something like 'USharpEventDispatcher' and if not possible, maybe a section in the discord could be 'incompatible unreal plugins'.

Of course after uninstalling the plugin from the project, all seems to work fine (for a 0.10 version :))

**Comment by OlssonDev** [comment]
Those class names will be removed once delegates are implemented. The EventDispatcher class is not in use and will be removed.
