### ISSUE TITLE
Blueprint Function Library function needs object reference

### ISSUE THREAD

**Issue by HOCKI1** [UnrealSharp/UnrealSharp#70]
Now it looks like this:
![image](https://github.com/UnrealSharp/UnrealSharp/assets/75937808/869cc435-bac0-461f-ae0e-1949bcfc6e91)
It should look like:
![image](https://github.com/UnrealSharp/UnrealSharp/assets/75937808/24ab8da4-c189-40af-ac8e-9f95f57b0ca8)

Code I used
```
using UnrealSharp.Attributes;
using UnrealSharp.Engine;

namespace ManagedMyProject3;

//Currently UClass attribute is a must for the editor to recognize the class
[UClass]
public class Test3 : BlueprintFunctionLibrary
{
    protected Test3(IntPtr nativeObject) : base(nativeObject)
    {
    }

    [UFunction(FunctionFlags.BlueprintCallable)]
    public void MyFunction5()
    {
        PrintString("Called MyFunc5");
    }
}
```

**Comment by OlssonDev** [comment]
This is not a bug. You need to define your function as static.
