### ISSUE TITLE
open crashes

### ISSUE THREAD

**Issue by songsgroup** [UnrealSharp/UnrealSharp#80]
UnrealSharpBuildTool with args (--Action GenerateProject --EngineDirectory "C:/Program Files/Epic Games/UE_5.3/Engine/" --ProjectDirectory "D:/program/A_UE/testuesharp/" --ProjectName testuesharp --PluginDirectory "D:/program/A_UE/testuesharp/Plugins/UnrealSharp" --OutputPath "D:/program/A_UE/testuesharp/Binaries/UnrealSharp") took 1.697042 seconds to execute.
Couldn't find Hostfxr.dll

Script Stack (0 frames) :

appError called: Fatal error: [File:D:\program\A_UE\testuesharp\Plugins\UnrealSharp\Source\CSharpForUE\CSManager.cpp] [Line: 98] 
Failed to load Runtime Host

dotnet 8.0.0,8.0.2

**Comment by OlssonDev** [comment]
Install DotNet 8.1
